import "../styles/global.css";
import { Metadata } from "next";
import Navigation from "../components/navigation";

// metadata 설정 (title, description)
// title은 %s를 사용하여 동적으로 설정할 수 있음
// default는 title이 설정되지 않았을 때 사용할 기본 값
export const metadata: Metadata = {
  title: {
    // template 사용하면 %s를 사용하여 동적으로 설정할 수 있음
    template: "%s | Next Movie🍿",
    default: "Loading...",
  },
  description: "Generated by Han",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
